language: java
jdk: oraclejdk8
services:
  - docker
script:
- gcloud -q preview app deploy app.yaml --set-default 
- python e2e_test.py
deploy:
  provider: gae
  keyfile: My First Project-638bad621412.json
  project: zippy-aurora-237105
  skip_cleanup: true
  default: true
