language: java
jdk: oraclejdk8
services:
  - docker
before_install:
- openssl aes-256-cbc -K $encrypted_45d1b36fa803_key -iv $encrypted_45d1b36fa803_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d $HOME/google-cloud-sdk ]; then  
    curl https://sdk.cloud.google.com | bash;
  fi
- tar -xzf credentials.tar.gz
- mkdir -p lib
- ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
- gcloud auth activate-service-account --key-file client-secret.json
script:
- gcloud -q preview app deploy app.yaml --set-default 
- python e2e_test.py
deploy:
  provider: gae
  keyfile: My First Project-638bad621412.json
  project: zippy-aurora-237105
  skip_cleanup: true
  default: true
